development:
  election_status: close
  positions:
    president: 1
    vice_president: 1
    senator: 12
    governor: 1
    vice_governor: 1
    mayor: 1
    vice_mayor: 1
    councilor: 6
    representative: 1

test:
  election_status: close
  positions:
    president: 1
    vice_president: 1
    senator: 12
    governor: 1
    vice_governor: 1
    mayor: 1
    vice_mayor: 1
    councilor: 6
    representative: 1

production:
  election_status: close
  positions:
    president: 1
    vice_president: 1
    senator: 12
    governor: 1
    vice_governor: 1
    mayor: 1
    vice_mayor: 1
    councilor: 6
    representative: 1

