development:
  election_status: close
  positions:
    'President': 1
    'Vice President': 1
    'Senator': 12
    'Governor': 1
    'Vice Governor': 1
    'Mayor': 1
    'Vice Mayor': 1
    'Councilor': 6
    'Representative': 1

test:
  election_status: close
  positions:
    'President': 1
    'Vice President': 1
    'Senator': 12
    'Governor': 1
    'Vice Governor': 1
    'Mayor': 1
    'Vice Mayor': 1
    'Councilor': 6
    'Representative': 1

production:
  election_status: close
  positions:
    'President': 1
    'Vice President': 1
    'Senator': 12
    'Governor': 1
    'Vice Governor': 1
    'Mayor': 1
    'Vice Mayor': 1
    'Councilor': 6
    'Representative': 1

