Abra: ABR1
Agusan del Norte: AGN1, AGN2
Agusan del Sur: AGS1, AGS2
Aklan: AKL1
Albay: ALB1, ALB2, ALB3
Antique: ANT1
Apayao: APA1
Aurora: AUR1
Basilan: BAS1
Bataan: BAT1, BAT2
Batanes: BTN1
Batangas: BTG1, BTG2, BTG3, BTG4
Benguet: BEN1
Biliran: BIL1
Bohol: BHL1, BHL2, BHL3
Bukidnon: BKN1, BKN2, BKN3
Bulacan: BUL1, BUL2, BUL3, BUL4
Cagayan: CAG1, CAG2, CAG3
Camarines Norte: CMN1, CMN2
Camarines Sur: CMS1, CMS2, CMS3, CMS4, CMS5
Camiguin: CAM1
Capiz: CPZ1, CPZ2
Catanduanes: CAT1
Cavite: CVT1, CVT2, CVT3, CVT4, CVT5, CVT6
Cebu: CEB1, CEB2, CEB3, CEB4, CEB5, CEB6
Compostela Valley: CPV1, CPV2
Cotabato: COT1, COT2
Davao del Norte: DVN1, DVN2
Davao del Sur: DVS1, DVS2
Davao Oriental: DVO1, DVO2
Dinagat Islands: 1
Eastern Samar: EAS1
Guimaras: GMR1
Ifugao: IFU1
Ilocos Norte: ILN1, ILN2
Ilocos Sur: ILS1, ILS2
Iloilo: ILO1, ILO2, ILO3, ILO4, ILO5
Isabela: ISA1, ISA2, ISA3, ISA4
Kalinga: KAL1
La Union: LUN1, LUN2
Laguna: LGN1, LGN2, LGN3, LGN4
Lanao del Norte: LNN1, LNN2
Lanao del Sur: LNS1, LNS2
Leyte: LEY1, LEY2, LEY3, LEY4, LEY5
Maguindanao: MAG1, MAG2
Marinduque: MAR1
Masbate: MSB1, MSB2, MSB3
Misamis Occidental: MSO1, MSO2
Misamis Oriental: MSR1, MSR2
Mountain Province: MTP1
Negros Occidental: NEO1, NEO2, NEO3, NEO4, NEO5, NEO6
Negros Oriental: NER1, NER2, NER3
Northern Samar: NOS1, NOS2
Nueva Ecija: NUE1, NUE2, NUE3, NUE4
Nueva Vizcaya: NUV1
Occidental Mindoro: OCM1
Oriental Mindoro: ORM1, ORM2
Palawan: PLW1, PLW2
Pampanga: PAM1, PAM2, PAM3, PAM4
Pangasinan: PAN1, PAN2, PAN3, PAN4, PAN5, PAN6
Quezon: QZN1, QZN2, QZN3, QZN4
Quirino: QRN1
Rizal: RZL1, RZL2
Romblon: RMB1
Samar: SMR1, SMR2
Sarangani: SRG1
Siquijor: SQJ1
Sorsogon: SOR1, SOR2
South Cotabato: SOC1, SOC2
Southern Leyte: SOL1
Sultan Kudarat: STK1
Sulu: SUL1, SUL2
Surigao del Norte: SUN1, SUN2
Surigao del Sur: SUS1, SUS2
Tarlac: TAR1, TAR2, TAR3
Tawi-Tawi: TWT1
Zambales: ZMB1, ZMB2
Zamboanga del Norte: ZBN1, ZBN2, ZBN3
Zamboanga del Sur: ZBS1, ZBS2
Zamboanga Sibugay: ZBY1, ZBY2

Antipolo City: ANT1, ANT2
Bacolod City: BCL1
Baguio City: BAG1
Cagayan de Oro City: CGY1, CGY2
Caloocan City: CLC1, CLC2
Cebu City: CEB1, CEB2
Dasmariñas City: DSM1
Davao City: DAV1, DAV2, DAV3
Iligan City: ILG1
Iloilo City: ILL1
Lapu-Lapu City: LPL1
Las Piñas City: LSP1
Makati City: MKT1, MKT2
Malabon City and Navotas City: MNV1, MNV2
Mandaluyong City: MND1
Manila City: MNL1, MNL2, MNL3, MNL4, MNL5, MNL6
Marikina City: MRK1, MRK2
Muntinlupa City: MNT1
Parañaque City: PRN1, PRN2
Pasay City: PSY1
Pasig City: PSG1
Pateros and Taguig City: PTG1
Quezon City: QZN1, QZN2, QZN3, QZN4
San Jose del Monte City: SJS1
San Juan City: SJN1
Taguig City: TGG1
Valenzuela City: VLN1, VLN2
Zamboanga City: ZMB1, ZMB2
