Abra: ABR
Agusan del Norte: AGN
Agusan del Sur: AGS
Aklan: AKL
Albay: ALB
Antique: ANT
Apayao: APA
Aurora: AUR
Basilan: BAS
Bataan: BAT
Batanes: BTN
Batangas: BTG
Benguet: BEN
Biliran: BIL
Bohol: BHL
Bukidnon: BKN
Bulacan: BUL
Cagayan: CAG
Camarines Norte: CMN
Camarines Sur: CMS
Camiguin: CAM
Capiz: CPZ
Catanduanes: CAT
Cavite: CVT
Cebu: CEB
Compostela Valley: CPV
Cotabato: COT
Davao del Norte: DVN
Davao del Sur: DVS
Davao Oriental: DVO
Eastern Samar: EAS
Guimaras: GMR
Ifugao: IFU
Ilocos Norte: ILN
Ilocos Sur: ILS
Iloilo: ILO
Isabela: ISA
Kalinga: KAL
La Union: LUN
Laguna: LGN
Lanao del Norte: LNN
Lanao del Sur: LNS
Leyte: LEY
Maguindanao: MAG
Marinduque: MAR
Masbate: MSB
Metro Manila: MML
Misamis Occidental: MSO
Misamis Oriental: MSR
Mountain Province: MTP
Negros Occidental: NEO
Negros Oriental: NER
Northern Samar: NOS
Nueva Ecija: NUE
Nueva Vizcaya: NUV
Occidental Mindoro: OCM
Oriental Mindoro: ORM
Palawan: PLW
Pampanga: PAM
Pangasinan: PAN
Quezon: QZN
Quirino: QRN
Rizal: RZL
Romblon: RMB
Samar: SMR
Sarangani: SRG
Siquijor: SQJ
Sorsogon: SOR
South Cotabato: SOC
Southern Leyte: SOL
Sultan Kudarat: STK
Sulu: SUL
Surigao del Norte: SUN
Surigao del Sur: SUS
Tarlac: TAR
Tawi-Tawi: TWT
Zambales: ZMB
Zamboanga del Norte: ZBN
Zamboanga del Sur: ZBS
Zamboanga Sibugay: ZBY
